### ISSUE TITLE
Crash when starting a server

### ISSUE THREAD

**Issue by MK-404** [Xwaffle1/CobblemonExtras#10]
[latest.log](https://github.com/Xwaffle1/CobblemonExtras/files/13199864/latest.log)

**Comment by cubicconjure** [comment]
It looks like you're missing [Architectury API](https://modrinth.com/mod/architectury-api). I was also having this problem, which we could have determined that by this in the log:
`Caused by: java.lang.ClassNotFoundException: dev.architectury.event.events.common.CommandRegistrationEvent`

I see the "ARCHITECTURE MOD REQUIRED" on the Modrinth changelog page now, but it would be preferred if on game load it would require Architectury API instead of attempting to launch and crashing with need to inspect a stack trace. So, feature request if that's appropriate? Or at least mentioned somewhere more prominent like the main Modrinth screen.

**Comment by Xwaffle1** [comment]
No longer an issue
